---
kind: pipeline
type: kubernetes
name: default

steps: 
- name: Semantical Versionning
  image: python:3.6
  commands:
    - mkdir ~/.ssh
    - echo $CI_SSH_KEY > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - pip install -r .semver/requirements.txt
    - python .semver/main.py
  environment:
    CI_REPOSITORY_URL:
      from_secret: CI_REPOSITORY_URL
    CI_SSH_KEY:
      from_secret: CI_SSH_KEY
  when:
    branch:
    - master
    event: push